# Generated by Django 4.2.6 on 2023-10-26 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_campus_options'),
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.address', verbose_name='Address'),
            preserve_default=False,
        ),
    ]
