# Generated by Django 4.2.6 on 2023-10-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_alter_newuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
    ]
