# Generated by Django 4.2.6 on 2023-10-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_address_unit_no'),
        ('customUser', '0004_alter_newuser_address_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address', verbose_name='Address'),
        ),
    ]
