# Generated by Django 4.2.6 on 2023-10-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_newuser_campus_staff_designation_staff_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
