# Generated by Django 4.2.6 on 2023-10-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_staff_temp_id_student_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
