# Generated by Django 4.2.6 on 2023-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0009_newuser_temp_id_staff_student_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
