# Generated by Django 4.2.6 on 2023-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0011_student_email_id_student_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
