# Generated by Django 4.2.6 on 2023-10-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0012_alter_student_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visa_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
