# Generated by Django 4.2.6 on 2023-10-30 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_id_alter_campus_id'),
        ('customUser', '0013_alter_student_visa_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='visa_expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
