# Generated by Django 4.2.6 on 2023-12-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0019_alter_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('HR', 'Human Resources'), ('Lecturer', 'Lecturer'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Counselor', 'Counselor'), ('Program Leader', 'Program Leader')], max_length=255, null=True),
        ),
    ]
