# Generated by Django 4.2.6 on 2023-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0020_alter_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('HR', 'Human Resources'), ('Lecturer', 'Lecturer'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Counselor', 'Counselor'), ('Program Leader', 'Program Leader'), ('Head of School', 'Head of School')], max_length=255, null=True),
        ),
    ]
