# Generated by Django 4.2.6 on 2023-12-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_id_alter_campus_id'),
        ('customUser', '0021_alter_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.campus', verbose_name='Campus'),
        ),
    ]
