# Generated by Django 4.2.6 on 2024-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0022_alter_newuser_address_alter_newuser_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='newuser',
            name='ethnicities',
            field=models.ManyToManyField(blank=True, null=True, to='customUser.ethnicity'),
        ),
    ]
