# Generated by Django 4.2.6 on 2024-01-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0023_ethnicity_newuser_ethnicities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'verbose_name': 'Ethnicity', 'verbose_name_plural': 'Ethncitites'},
        ),
    ]
