# Generated by Django 4.2.6 on 2024-01-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0024_alter_ethnicity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='fund_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customUser.studentfundsource', verbose_name='Student Fund Source'),
        ),
    ]
