# Generated by Django 4.2.6 on 2024-01-02 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0025_studentfundsource_student_fund_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfundsource',
            name='name',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
