# Generated by Django 5.0.1 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
