# Generated by Django 4.2.6 on 2023-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='courses', to='program.program'),
        ),
    ]
