# Generated by Django 4.2.6 on 2023-10-26 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_newuser_campus_staff_designation_staff_joining_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0002_remove_course_program_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOffering',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('active_status', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='program')),
                ('student', models.ManyToManyField(blank=True, related_name='offered_program', to='customUser.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
