# Generated by Django 4.2.6 on 2023-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0006_newuser_campus_staff_designation_staff_joining_date_and_more'),
        ('program', '0003_programoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoffering',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='programs', to='customUser.student'),
        ),
    ]
