# Generated by Django 4.2.6 on 2023-10-27 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_staff_temp_id_student_temp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0004_alter_programoffering_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='course', to='program.program'),
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='program_offering', to='customUser.student'),
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('temp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('active_status', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.course', verbose_name='course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, related_name='course_offering', to='customUser.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
