# Generated by Django 4.2.6 on 2023-10-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_course_temp_id_program_temp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration_in_month',
            new_name='duration_in_week',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='duration_in_month',
            new_name='duration_in_week',
        ),
    ]
