# Generated by Django 4.2.6 on 2023-10-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_alter_course_active_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
