# Generated by Django 4.2.6 on 2023-10-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0014_alter_newuser_campus_alter_newuser_dob_and_more'),
        ('program', '0009_alter_course_id_alter_courseoffering_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_offering', to='customUser.student'),
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='program'),
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='program_offering', to='customUser.student'),
        ),
    ]
