# Generated by Django 4.2.6 on 2023-10-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_course_course_efts_alter_courseoffering_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_efts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
