# Generated by Django 4.2.6 on 2023-11-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_courseoffering_result_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offering', to='program.course', verbose_name='course'),
        ),
    ]
