# Generated by Django 4.2.6 on 2023-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0015_rename_student_email_id_staff_email_id_and_more'),
        ('program', '0014_alter_courseoffering_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='course_offerings', to='customUser.student'),
        ),
    ]
