# Generated by Django 4.2.6 on 2023-11-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_alter_courseoffering_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoffering',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_offerings', to='program.program', verbose_name='program'),
        ),
    ]
