# Generated by Django 4.2.6 on 2023-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0016_alter_newuser_campus_alter_staff_staff_and_more'),
        ('program', '0016_alter_programoffering_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='course_offerings', to='customUser.staff'),
        ),
    ]
