# Generated by Django 4.2.6 on 2024-01-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_programoffering_program_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAndCourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Program and Course Type',
                'verbose_name_plural': 'Program and Course Type',
            },
        ),
        migrations.AddField(
            model_name='programoffering',
            name='offering_mode',
            field=models.CharField(blank=True, choices=[('online', 'ONLINE'), ('micro cred', 'MICRO CRED'), ('blended', 'BLENDED')], default='online', help_text='Select the mode of course offering: Online, Offline, or Blended', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='offering_mode',
            field=models.CharField(blank=True, choices=[('online', 'ONLINE'), ('micro cred', 'MICRO CRED'), ('blended', 'BLENDED')], default='online', help_text='Select the mode of course offering: Online, Offline, or Blended', max_length=10, null=True),
        ),
    ]
