# Generated by Django 5.0.1 on 2024-02-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_programandcoursetype_programoffering_offering_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='courses', to='program.program'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='program.course', verbose_name='course'),
        ),
    ]
