# Generated by Django 5.0.1 on 2024-02-27 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0021_alter_course_program_alter_courseoffering_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCourseOfferingRelations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('active_status', models.BooleanField(default=True)),
                ('students_by_campus', models.CharField(choices=[(uuid.UUID('7a6430db-3c57-4c5b-a6ad-eb3d74869fe8'), 'Auckland (Computer Power Plus)'), (uuid.UUID('583c2bda-9db6-4ec2-b7ac-cf8e3a17d44b'), 'Christchurch (Computer Power Plus)'), (uuid.UUID('e450a8af-de83-4253-b155-ab4b8fdbd70c'), 'Manukau (Whitecliffe)'), (uuid.UUID('c0295d21-1f15-41ca-a35b-49fb2cf56464'), 'Wellington (Computer Power Plus)'), (uuid.UUID('8b285439-a088-4465-b2d0-6525104e24f7'), 'Courses delivered extramurally or by distance'), ('all', 'All')], default='all', max_length=100, verbose_name='campus')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_course_offering_relations', to='program.courseoffering', verbose_name='course_offering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_course_offering_relations', to='customUser.staff', verbose_name='staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
