# Generated by Django 5.0.1 on 2024-04-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0024_staffprogramrelations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffprogramofferingrelations',
            unique_together={('staff', 'program_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='staffprogramrelations',
            unique_together={('staff', 'program')},
        ),
    ]
