# Generated by Django 5.0.1 on 2024-04-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0025_alter_staffprogramofferingrelations_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcourseofferingrelations',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_course_offering_relations', to='customUser.staff', verbose_name='staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffcourseofferingrelations',
            unique_together={('staff', 'course_offering')},
        ),
    ]
