# Generated by Django 5.0.1 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_alter_staffcourseofferingrelations_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffcourseofferingrelations',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprogramofferingrelations',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprogramrelations',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffcourseofferingrelations',
            name='students_by_campus',
            field=models.CharField(choices=[], default='all', max_length=100, verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='staffprogramofferingrelations',
            name='students_by_campus',
            field=models.CharField(choices=[], default='all', max_length=100, verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='staffprogramrelations',
            name='students_by_campus',
            field=models.CharField(choices=[], default='all', max_length=100, verbose_name='campus'),
        ),
    ]
