# Generated by Django 4.2.6 on 2023-10-26 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_programoffering_student'),
        ('customUser', '0006_newuser_campus_staff_designation_staff_joining_date_and_more'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_status', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.course')),
                ('program_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUser.student')),
            ],
            options={
                'unique_together': {('student', 'program_offering', 'course')},
            },
        ),
    ]
