# Generated by Django 4.2.6 on 2023-10-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_attendance_attendance_date_courseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
