# Generated by Django 4.2.6 on 2023-10-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_attendance_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
