# Generated by Django 4.2.6 on 2023-11-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0015_rename_student_email_id_staff_email_id_and_more'),
        ('program', '0014_alter_courseoffering_course'),
        ('report', '0005_alter_attendance_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courseoffering'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='course_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.courseoffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseresult',
            name='result_status_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='program_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programoffering'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customUser.student'),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='program_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programoffering'),
        ),
        migrations.AlterField(
            model_name='courseresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customUser.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'program_offering', 'course_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='courseresult',
            unique_together={('student', 'program_offering', 'course_offering')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseresult',
            name='course',
        ),
    ]
