# Generated by Django 4.2.6 on 2023-11-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attended',
            new_name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remark',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
