# Generated by Django 4.2.6 on 2023-11-08 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_rename_attended_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
