# Generated by Django 4.2.6 on 2023-11-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_attendance_remark_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('informed absent', 'Informed Absent'), ('tardy', 'Tardy')], default='present', max_length=255, null=True),
        ),
    ]
