# Generated by Django 4.2.6 on 2023-11-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_weeklyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='session_number',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='sessions',
            field=models.ManyToManyField(to='report.attendance', verbose_name='sessions'),
        ),
    ]
