# Generated by Django 4.2.6 on 2023-11-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0015_rename_student_email_id_staff_email_id_and_more'),
        ('report', '0011_remove_weeklyreport_session_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_weekly_reports', to='customUser.student', verbose_name='Course Offering'),
        ),
    ]
