# Generated by Django 4.2.6 on 2023-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_alter_weeklyreport_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='action',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('follow up email and call', 'Follow Up Email and Call'), ('pastoral care', 'Pastoral Care'), ('personalised study plan/Extra session', 'Personlaised Study Plan /Extra Session'), ('emergency contact', 'Emergency Contact'), ('other', 'Other')], default='n/a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='engagement',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('on track canvas', 'On Track - CANVAS'), ('on track assessment', 'On Track - Assessment'), ('on track learning activity', 'On Track - Learning Activity'), ('on track blended', 'On Track - Blended'), ('not engaged', 'Not Engaged')], default='n/a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='follow_up',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('warning letter 1', 'Warning Letter 1'), ('warning letter 2', 'Warning Letter 2')], default='n/a', max_length=255, null=True),
        ),
    ]
