# Generated by Django 4.2.6 on 2023-11-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_weeklyreport_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='login_in_on_canvas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='no_of_pages_viewed_on_canvas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='performance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
