# Generated by Django 4.2.6 on 2023-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_weeklyreport_login_in_on_canvas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='performance',
            field=models.CharField(blank=True, choices=[('poor', 'POOR'), ('good', 'GOOD'), ('moderate', 'MODERATE')], max_length=255, null=True),
        ),
    ]
