# Generated by Django 4.2.6 on 2023-12-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_alter_weeklyreport_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='performance',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='assessment_status',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('making progress', 'MAKING PROGRESS '), ('no progress', 'NO PROGRESS'), ('request extension', 'REQUEST EXTENSION'), ('submitted', 'SUBMITTED'), ('not submitted', 'NOT SUBMITTED'), ('failed', 'FAILED'), ('re-sit', 'RE-SIT')], default='n/a', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='at_risk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
