# Generated by Django 4.2.6 on 2023-12-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_courseoffering_offering_mode'),
        ('report', '0018_remove_weeklyreport_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='program.courseoffering'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='at_risk',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
