# Generated by Django 4.2.6 on 2024-01-02 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0023_ethnicity_newuser_ethnicities'),
        ('report', '0019_alter_attendance_course_offering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='customUser.student'),
        ),
    ]
