# Generated by Django 5.0.1 on 2024-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_alter_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='weekly_reports',
            field=models.ManyToManyField(related_name='attendances', to='report.weeklyreport'),
        ),
    ]
