# Generated by Django 5.0.1 on 2024-01-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0020_programandcoursetype_programoffering_offering_mode_and_more'),
        ('report', '0021_attendance_weekly_reports'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='program_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='program.programoffering'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='program.courseoffering', verbose_name='Course Offering'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'program_offering', 'course_offering', 'attendance_date')},
        ),
    ]
