# Generated by Django 5.0.1 on 2024-02-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_alter_course_program_alter_courseoffering_course'),
        ('report', '0022_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='program.courseoffering'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='action',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('follow up email and call', 'Follow Up Email and Call'), ('pastoral care', 'Pastoral Care'), ('personalized study plan/Extra session', 'Personalized Study Plan /Extra Session'), ('emergency contact', 'Emergency Contact'), ('other', 'Other')], default='n/a', max_length=255, null=True),
        ),
    ]
