# Generated by Django 5.0.1 on 2024-02-24 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0021_alter_course_program_alter_courseoffering_course'),
        ('report', '0023_alter_attendance_course_offering_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('active_status', models.BooleanField(default=True)),
                ('status', models.BooleanField()),
                ('result', models.CharField(blank=True, choices=[('awaited', 'Awaited'), ('pass', 'Pass'), ('fail', 'Fail'), ('dropped', 'Dropped')], default='awaited', max_length=255, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.courseoffering', verbose_name='course_offering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.programoffering', verbose_name='program_offering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUser.student', verbose_name='student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
