# Generated by Django 5.0.1 on 2024-02-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0021_alter_course_program_alter_courseoffering_course'),
        ('report', '0024_studentenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='program.courseoffering', verbose_name='course_offering'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='program_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='program.programoffering', verbose_name='program_offering'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='customUser.student', verbose_name='student'),
        ),
    ]
