# Generated by Django 5.0.1 on 2024-03-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_alter_studentenrollment_course_offering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='action',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('follow up email and call', 'Follow Up Email and Call'), ('pastoral care', 'Pastoral Care'), ('personalized study plan/Extra session', 'Personalized Study Plan / Extra Session'), ('emergency contact', 'Emergency Contact'), ('other', 'Other')], default='na', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='engagement',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('on track canvas', 'On Track - CANVAS'), ('on track assessment', 'On Track - Assessment'), ('on track learning activity', 'On Track - Learning Activity'), ('on track blended', 'On Track - Blended'), ('not engaged', 'Not Engaged')], default='na', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='follow_up',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('warning letter 1', 'Warning Letter 1'), ('warning letter 2', 'Warning Letter 2')], default='na', max_length=255, null=True),
        ),
    ]
