# Generated by Django 5.0.1 on 2024-04-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0026_alter_studentfundsource_name'),
        ('program', '0024_staffprogramrelations'),
        ('report', '0026_alter_weeklyreport_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='at_risk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course_offering', 'attendance_date')},
        ),
    ]
