# Generated by Django 5.0.1 on 2024-04-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_alter_weeklyreport_at_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='week_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
