# Generated by Django 5.0.1 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
