# Generated by Django 4.2.6 on 2023-10-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_csv_alter_uploadfile_active_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
