# Generated by Django 5.0.1 on 2024-03-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0005_canvasstatsupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='upload-bulk-attendance')),
                ('time_table', models.FileField(upload_to='upload-bulk-attendance/time-table')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
