# Generated by Django 4.2.6 on 2023-10-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
    ]
