# Generated by Django 4.2.6 on 2023-10-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_campus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='unit_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
