# Generated by Django 4.2.6 on 2023-10-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_address_unit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='temp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
