# Generated by Django 4.2.6 on 2023-10-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_address_temp_id_campus_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
