# Generated by Django 5.0.1 on 2024-02-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_id_alter_campus_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='base.address'),
        ),
    ]
