# Generated by Django 5.0.1 on 2024-05-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_campus_options_alter_campus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
